### ISSUE TITLE
Is this Project dead?

### ISSUE THREAD

**Issue by thetruestarr1337** [skanatiker/ark_server_manager#2]
I wanted to use this Server Manager on my Linux Server.. last updates are from 3months ago. Is this project still maintained?

**Comment by skanatiker** [comment]
Hey Truestarr, i am currently not working actively on the project. I am not playing Arc anymore myself and there has only been a very little interest on this project. So currently i do not intent to develop new features, but if issues occur i will definetly try to fix them and try to support everyone who wants to get this server manager up and running. If someone creates a Pull Request for the project i will of course also have look at it and integrate it.

**Comment by thetruestarr1337** [comment]
Okay, good to know :) thanks
