### ISSUE TITLE
What should i do?

### ISSUE THREAD

**Issue by Bierziege** [skanatiker/ark_server_manager#3]
Hi, i want to install this to my linux64 server:

https://github.com/skanatiker/ark_server_manager

> `git clone https://github.com/skanatiker/ark_server_manager` to download the program
> `npm install` to load all required dependencies
> `node server.js` to start the server

`
# npm install
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3

npm ERR! No compatible version found: asn1js@^0.2.3
npm ERR! Valid install targets:
npm ERR! 1.2.12, 1.2.11, 1.2.10, 1.2.9, 1.2.8, 1.2.4, 1.2.3, 1.2.2, 1.0.2, 1.0.1
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /root/ark_server_manager/npm-debug.log

[npm-debug.txt](https://github.com/npm/npm/files/412424/npm-debug.txt)

# node server.js
bash: /usr/sbin/node: No such file or directory

`What should I do to run the right version?
Can someone Help me?

Much thanks 
Bierziege

**Comment by error418** [comment]
There seems to be a problem with a required dependency.
`asn1js` does not have a version named `0.2.3`.
`asn1`  on the other hand has this version.

@skanatiker maybe update the versions using `npm-check-updates`?

**Comment by error418** [comment]
The affected dependency tree is
```
`-- letsencrypt-express@1.2.0
  `-- letsencrypt@1.5.7
    `-- asn1js@1.2.12
```

**Comment by Bierziege** [comment]
Thank you for your answer!

```
# npm-check updates
bash: npm-check: command not found
# npm-check -updates
bash: npm-check: command not found
# npm-check-updates
bash: npm-check-updates: command not found
```

You may mean `npm update`.

I used it and i got this:
```
# npm update
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

> ursa@0.9.4 install /USER/ark_server_manager/node_modules/ursa
> node-gyp rebuild

make: Entering directory '/USER/ark_server_manager/node_modules/ursa/build'
  CXX(target) Release/obj.target/ursaNative/src/ursaNative.o
  SOLINK_MODULE(target) Release/obj.target/ursaNative.node
  COPY Release/ursaNative.node
make: Leaving directory '/USER/ark_server_manager/node_modules/ursa/build'
ArkServerManager@0.1.0 /USER/ark_server_manager
├── body-parser@1.15.2
├── express@4.14.0
├── express-jwt@3.4.0
├── gulp@3.9.1
├── gulp-angular-templatecache@1.9.1
├── gulp-concat@2.6.0
├── gulp-ng-annotate@0.3.6
├── gulp-sourcemaps@1.6.0
├── gulp-uglify@0.3.2
├── gulp-util@3.0.1
├── helmet@1.3.0
├── jsonwebtoken@5.7.0
├── letsencrypt-express@1.2.0
├── morgan@1.7.0
├── nedb@1.8.0
├── spdy@3.4.0
└── ws@1.1.1

npm WARN ArkServerManager@0.1.0 No repository field.
npm WARN ArkServerManager@0.1.0 No license field.
```

Now everything work fine!
Thanky ou realy much!

**Comment by error418** [comment]
Yes, a `npm update` is also fine to fix your problem locally :)

On a litte side-note:
[npm-check-updates](https://www.npmjs.com/package/npm-check-updates) is meant to be used to fix the packages in the `package.json`, so no one will run in your reported issue anymore when trying to retrieve the dependencies ;)

As long the versions in the `package.json` are not updated the code in the repository can not be built.

Anyway.. have fun playing Ark :)

**Comment by skanatiker** [comment]
Thx for reporting this issue @Bierziege and thx for your support @error418.

I updated the library versions, so the issue should not occur anymore.
