### ISSUE TITLE
Infos?

### ISSUE THREAD

**Issue by DiTechRacer** [skanatiker/ark_server_manager#5]
Hallo,

gibts irgendwie auch ne demo von den WI? Screenshots würden ja schon reichen.
Des weiteren suche ich jemanden der mir etwas bei der Installation hilft. Bekomme es nicht zum laufen. Hauptsächlich macht mir die HTTPS geschichte Probleme.

Bin Dankbar für jede Antwort.

Gruß Tim

**Comment by skanatiker** [comment]
Hallo DiTechRacer,

ich werde schauen, dass ich noch Screenshots hinzufüge. Vielen Dank für dein Feedback!

Bzgl der HTTPS Problematik ... kannst du das noch etwas genauer beschreiben? Wie möchtest du den Server genau betreiben? Hast du einen Linuxrechner bei dir im LAN, oder hast du einen Root Server auf dem es läuft, etc?

An sich sollte das Zertifikat beim Starten des Servers einfach generiert werden. Es ist allerdings immernoch der Status, dass es kein valides Zertifikat ist. Dein Browser wird also beim Aufruf der Seite eine Warnung ausgeben, dass das Zertifkat nicht validiert werden konnte. Du kannst dann aber auswählen, dass du dem Zertifikat dennoch vertrauen möchtest.

Generell würden wie gesagt weitere Hintergrundinformationen und mehr Details zu den Problemen bei der Installation helfen. Auch ggf Fehlermeldungen oder Ausgaben auf der Konsole können helfen.

Gruß,
skanatiker

**Comment by DiTechRacer** [comment]
Hey,

zuerst mal, ignoriere meine E-Mail! Die ging zu spät raus ;)

Also ich habe einen ARK Server auf meinem vServer am laufen. Möchte das WI für ein paar Kollegen, damit die auch mal neustarten können. Ich habe 3000 und 3001 sowohl als TCP als auch UDP frei gegeben. Alles nach Anleitung installiert. Aber ich komme nicht ins Interface.
Ich weiss ja nicht wie weit dein support geht. Aber wenn du mal zeit für TS oder Skype hättest wäre das schon extrem geil!

**Comment by DiTechRacer** [comment]
Hey,

vielen Dank für den Super Support! Der Server Läuft perfekt mit diesem Webinterface! Mods wurden auch geladen. Alles optimal. Jetzt muss nur noch die Installationsanleitung angepasst werden ;)

Danke und Liebe Grüße Tim

**Comment by skanatiker** [comment]
Freut mich, dass ich helfen konnte. Ich habe die README angepasst, so dass nun die zuverlässige Variante der NodeJS Installation enthalten ist. 
Außerdem habe ich 2 Screenshots, die das Web Interface zeigen hinzugefügt.
